import { NavbarComp } from '../components/uiFrontend/navbar'
import '../globals.css'
// import { Header, Footer } from '@/components/Layout'
// import 'react-toastify/dist/ReactToastify.css'
export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function ContentRootLayout({ children } : any) {
  return (
    <>
      {/* <Header /> */}
      <NavbarComp />
      {children}
      {/* <Footer /> */}
    </>
  )
}